config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('custom_auth.urls')),
    path('transactions/', include('money_management.urls')),
    path('', include('landing_page.urls')),
    path('reports/', include('reports.urls')),
    path('budget_planning/', include('budget_planning.urls')),
]

money_management/urls.py
from django.urls import path
from .views import add_transaction, index, add_account, update_transaction, delete_transaction

app_name = 'money_management'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_transaction, name='add_transaction'),
    path('add_account/', add_account, name='add_account'),
    path('update/<int:pk>/', update_transaction, name='update_transaction'),
    path('delete/<int:pk>/', delete_transaction, name='delete_transaction'),
]

money_management/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    balance = models.DecimalField(max_digits=30, decimal_places=2)

    def __str__(self):
        return self.name

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
        }

class Transaction(models.Model):
    ACCOUNT_TYPES = [
        ('income', 'Income'),
        ('expense', 'Expense'),
    ]

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=ACCOUNT_TYPES)
    amount = models.DecimalField(max_digits=30, decimal_places=2)
    category = models.CharField(max_length=100)
    date = models.DateField()
    note = models.TextField(blank=True, null=True)
    previous_balance = models.DecimalField(max_digits=30, decimal_places=2, default=0)
    current_balance = models.DecimalField(max_digits=30, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.previous_balance = self.account.balance
        if self.type == 'income':
            self.account.balance += self.amount
        else:
            self.account.balance -= self.amount
        self.current_balance = self.account.balance
        self.account.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.account.name} - {self.type} - {self.amount}'

money_management/forms.py
from django import forms
from .models import Transaction, Account

CURRENCY_CHOICES = [
    ('AED', 'United Arab Emirates Dirham'),
    ('AFN', 'Afghan Afghani'),
    ('ALL', 'Albanian Lek'),
    ('AMD', 'Armenian Dram'),
    ('ANG', 'Netherlands Antillean Guilder'),
    ('AOA', 'Angolan Kwanza'),
    ('ARS', 'Argentine Peso'),
    ('AUD', 'Australian Dollar'),
    ('AWG', 'Aruban Florin'),
    ('AZN', 'Azerbaijani Manat'),
    ('BAM', 'Bosnia-Herzegovina Convertible Mark'),
    ('BBD', 'Barbadian Dollar'),
    ('BDT', 'Bangladeshi Taka'),
    ('BGN', 'Bulgarian Lev'),
    ('BHD', 'Bahraini Dinar'),
    ('BIF', 'Burundian Franc'),
    ('BMD', 'Bermudian Dollar'),
    ('BND', 'Brunei Dollar'),
    ('BOB', 'Bolivian Boliviano'),
    ('BRL', 'Brazilian Real'),
    ('BSD', 'Bahamian Dollar'),
    ('BTN', 'Bhutanese Ngultrum'),
    ('BWP', 'Botswana Pula'),
    ('BYN', 'Belarusian Ruble'),
    ('BZD', 'Belize Dollar'),
    ('CAD', 'Canadian Dollar'),
    ('CDF', 'Congolese Franc'),
    ('CHF', 'Swiss Franc'),
    ('CLP', 'Chilean Peso'),
    ('CNY', 'Chinese Yuan'),
    ('COP', 'Colombian Peso'),
    ('CRC', 'Costa Rican Colón'),
    ('CUP', 'Cuban Peso'),
    ('CVE', 'Cape Verdean Escudo'),
    ('CZK', 'Czech Koruna'),
    ('DJF', 'Djiboutian Franc'),
    ('DKK', 'Danish Krone'),
    ('DOP', 'Dominican Peso'),
    ('DZD', 'Algerian Dinar'),
    ('EGP', 'Egyptian Pound'),
    ('ERN', 'Eritrean Nakfa'),
    ('ETB', 'Ethiopian Birr'),
    ('EUR', 'Euro'),
    ('FJD', 'Fijian Dollar'),
    ('FKP', 'Falkland Islands Pound'),
    ('FOK', 'Faroese Króna'),
    ('GBP', 'British Pound'),
    ('GEL', 'Georgian Lari'),
    ('GGP', 'Guernsey Pound'),
    ('GHS', 'Ghanaian Cedi'),
    ('GIP', 'Gibraltar Pound'),
    ('GMD', 'Gambian Dalasi'),
    ('GNF', 'Guinean Franc'),
    ('GTQ', 'Guatemalan Quetzal'),
    ('GYD', 'Guyanese Dollar'),
    ('HKD', 'Hong Kong Dollar'),
    ('HNL', 'Honduran Lempira'),
    ('HRK', 'Croatian Kuna'),
    ('HTG', 'Haitian Gourde'),
    ('HUF', 'Hungarian Forint'),
    ('IDR', 'Indonesian Rupiah'),
    ('ILS', 'Israeli New Shekel'),
    ('IMP', 'Isle of Man Pound'),
    ('INR', 'Indian Rupee'),
    ('IQD', 'Iraqi Dinar'),
    ('IRR', 'Iranian Rial'),
    ('ISK', 'Icelandic Króna'),
    ('JEP', 'Jersey Pound'),
    ('JMD', 'Jamaican Dollar'),
    ('JOD', 'Jordanian Dinar'),
    ('JPY', 'Japanese Yen'),
    ('KES', 'Kenyan Shilling'),
    ('KGS', 'Kyrgyzstani Som'),
    ('KHR', 'Cambodian Riel'),
    ('KID', 'Kiribati Dollar'),
    ('KMF', 'Comorian Franc'),
    ('KRW', 'South Korean Won'),
    ('KWD', 'Kuwaiti Dinar'),
    ('KYD', 'Cayman Islands Dollar'),
    ('KZT', 'Kazakhstani Tenge'),
    ('LAK', 'Lao Kip'),
    ('LBP', 'Lebanese Pound'),
    ('LKR', 'Sri Lankan Rupee'),
    ('LRD', 'Liberian Dollar'),
    ('LSL', 'Lesotho Loti'),
    ('LYD', 'Libyan Dinar'),
    ('MAD', 'Moroccan Dirham'),
    ('MDL', 'Moldovan Leu'),
    ('MGA', 'Malagasy Ariary'),
    ('MKD', 'Macedonian Denar'),
    ('MMK', 'Burmese Kyat'),
    ('MNT', 'Mongolian Tögrög'),
    ('MOP', 'Macanese Pataca'),
    ('MRU', 'Mauritanian Ouguiya'),
    ('MUR', 'Mauritian Rupee'),
    ('MVR', 'Maldivian Rufiyaa'),
    ('MWK', 'Malawian Kwacha'),
    ('MXN', 'Mexican Peso'),
    ('MYR', 'Malaysian Ringgit'),
    ('MZN', 'Mozambican Metical'),
    ('NAD', 'Namibian Dollar'),
    ('NGN', 'Nigerian Naira'),
    ('NIO', 'Nicaraguan Córdoba'),
    ('NOK', 'Norwegian Krone'),
    ('NPR', 'Nepalese Rupee'),
    ('NZD', 'New Zealand Dollar'),
    ('OMR', 'Omani Rial'),
    ('PAB', 'Panamanian Balboa'),
    ('PEN', 'Peruvian Sol'),
    ('PGK', 'Papua New Guinean Kina'),
    ('PHP', 'Philippine Peso'),
    ('PKR', 'Pakistani Rupee'),
    ('PLN', 'Polish Złoty'),
    ('PYG', 'Paraguayan Guaraní'),
    ('QAR', 'Qatari Riyal'),
    ('RON', 'Romanian Leu'),
    ('RSD', 'Serbian Dinar'),
    ('RUB', 'Russian Ruble'),
    ('RWF', 'Rwandan Franc'),
    ('SAR', 'Saudi Riyal'),
    ('SBD', 'Solomon Islands Dollar'),
    ('SCR', 'Seychellois Rupee'),
    ('SDG', 'Sudanese Pound'),
    ('SEK', 'Swedish Krona'),
    ('SGD', 'Singapore Dollar'),
    ('SHP', 'Saint Helena Pound'),
    ('SLL', 'Sierra Leonean Leone'),
    ('SOS', 'Somali Shilling'),
    ('SRD', 'Surinamese Dollar'),
    ('SSP', 'South Sudanese Pound'),
    ('STN', 'São Tomé and Príncipe Dobra'),
    ('SYP', 'Syrian Pound'),
    ('SZL', 'Eswatini Lilangeni'),
    ('THB', 'Thai Baht'),
    ('TJS', 'Tajikistani Somoni'),
    ('TMT', 'Turkmenistani Manat'),
    ('TND', 'Tunisian Dinar'),
    ('TOP', 'Tongan Paʻanga'),
    ('TRY', 'Turkish Lira'),
    ('TTD', 'Trinidad and Tobago Dollar'),
    ('TVD', 'Tuvaluan Dollar'),
    ('TWD', 'New Taiwan Dollar'),
    ('TZS', 'Tanzanian Shilling'),
    ('UAH', 'Ukrainian Hryvnia'),
    ('UGX', 'Ugandan Shilling'),
    ('USD', 'United States Dollar'),
    ('UYU', 'Uruguayan Peso'),
    ('UZS', 'Uzbekistani Soʻm'),
    ('VES', 'Venezuelan Bolívar'),
    ('VND', 'Vietnamese Đồng'),
    ('VUV', 'Vanuatu Vatu'),
    ('WST', 'Samoan Tālā'),
    ('XAF', 'Central African CFA Franc'),
    ('XCD', 'East Caribbean Dollar'),
    ('XOF', 'West African CFA Franc'),
    ('XPF', 'CFP Franc'),
    ('YER', 'Yemeni Rial'),
    ('ZAR', 'South African Rand'),
    ('ZMW', 'Zambian Kwacha'),
    ('ZWL', 'Zimbabwean Dollar')
]

class TransactionForm(forms.ModelForm):
    currency = forms.ChoiceField(choices=CURRENCY_CHOICES, initial='USD', label='Currency')

    class Meta:
        model = Transaction
        fields = ['account', 'type', 'amount', 'category', 'date', 'note', 'currency']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'balance']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'balance': forms.NumberInput(attrs={'class': 'form-control'}),
        }

money_management/views.py
import json
import logging
from django.db.models import Sum
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TransactionForm, AccountForm
from .models import Transaction, Account
from budget_planning.models import  Notification, Plan
from .utils import convert_currency
from .forms import CURRENCY_CHOICES
from concurrent.futures import ThreadPoolExecutor
from django.core.paginator import Paginator
from django.http import JsonResponse


logger = logging.getLogger(__name__)
def convert_transaction(transaction, target_currency):
    converted_amount = convert_currency(transaction.amount, 'USD', target_currency)
    formatted_date = transaction.date.strftime('%B %d, %Y, %I:%M %p')
    formatted_created_at = transaction.created_at.strftime('%B %d, %Y, %I:%M %p')
    return {
        'id': transaction.id,
        'account': transaction.account.name,
        'type': transaction.get_type_display(),
        'previous_balance': convert_currency(transaction.previous_balance, 'USD', target_currency),
        'amount': converted_amount,
        'current_balance': convert_currency(transaction.current_balance, 'USD', target_currency),
        'category': transaction.category,
        'date': transaction.date,
        'note': transaction.note,
        'created_at': formatted_created_at,
        'currency': target_currency
    }


def add_transaction(request):
    date_str = request.GET.get('date', '')
    next_url = request.GET.get('next', 'money_management:index')
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            amount = form.cleaned_data['amount']
            currency = form.cleaned_data['currency']
            if currency != 'USD':
                transaction.amount = convert_currency(amount, currency, 'USD')
            transaction.save()
            check_budget(transaction)
            return redirect(next_url)
    else:
        form = TransactionForm(initial={'date': date_str})
    return render(request, 'money_management/add_transaction.html', {'form': form, 'next': next_url})

def add_account(request):
    next_url = request.GET.get('next', 'money_management:index')
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.user = request.user
            account.save()
            return redirect(next_url)
    else:
        form = AccountForm()
    return render(request, 'money_management/add_account.html', {'form': form, 'next': next_url})


def update_transaction(request, pk):
    transaction = get_object_or_404(Transaction, pk=pk)
    if request.method == 'POST':
        form = TransactionForm(request.POST, instance=transaction)
        if form.is_valid():
            form.save()
            return redirect('money_management:index')
    else:
        form = TransactionForm(instance=transaction)
    return render(request, 'money_management/update_transaction.html', {'form': form})


def delete_transaction(request, pk):
    transaction = get_object_or_404(Transaction, pk=pk)
    if request.method == 'POST':
        transaction.delete()
        return redirect('money_management:index')
    return render(request, 'money_management/delete_transaction.html', {'transaction': transaction})

logger = logging.getLogger(__name__)

def index(request):
    try:
        transactions = Transaction.objects.all().order_by('-created_at')
        paginator = Paginator(transactions, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        account_form = AccountForm()
        target_currency = request.GET.get('currency', 'USD')
        account_id = request.GET.get('account', None)
        chart_type = request.GET.get('chart_type', 'line')

        if account_id:
            transactions = transactions.filter(account_id=account_id)

        with ThreadPoolExecutor() as executor:
            converted_transactions = list(executor.map(lambda t: convert_transaction(t, target_currency), page_obj))

        date_field = 'date'
        daily_totals = transactions.extra({'date': "DATE(created_at)"}).values(date_field).annotate(total_amount=Sum('amount')).order_by(date_field)
        income_totals = transactions.filter(type='Income').extra({'date': "DATE(created_at)"}).values(date_field).annotate(total_amount=Sum('amount')).order_by(date_field)
        expense_totals = transactions.filter(type='Expense').extra({'date': "DATE(created_at)"}).values(date_field).annotate(total_amount=Sum('amount')).order_by(date_field)

        chart_data = {
            'labels': [str(item[date_field]) for item in daily_totals],
            'total': [float(item['total_amount']) for item in daily_totals],
            'income': [float(item['total_amount']) for item in income_totals],
            'expense': [float(item['total_amount']) for item in expense_totals],
        }

        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({
                'transactions': converted_transactions,
                'has_next': page_obj.has_next(),
                'next_page_number': page_obj.next_page_number() if page_obj.has_next() else None
            })

        return render(request, 'money_management/index.html', {
            'transactions': converted_transactions,
            'account_form': account_form,
            'target_currency': target_currency,
            'currency_choices': CURRENCY_CHOICES,
            'page_obj': page_obj,
            'chart_data': json.dumps(chart_data),
            'chart_type': chart_type,
            'account_id': account_id,
            'accounts': Account.objects.all(),
        })

    except Exception as e:
        logger.error(f"Error in index view: {str(e)}", exc_info=True)
        return JsonResponse({'error': 'Internal Server Error', 'details': str(e)}, status=500)


def check_budget(transaction):
    account = transaction.account
    user = account.user
    category = transaction.category

    budgets = Plan.objects.filter(user=user, category=category)
    if budgets.exists():
        budget = budgets.first()
        total_expenses = Transaction.objects.filter(
            account__user=user, category=category
        ).aggregate(total=Sum('amount'))['total'] or 0
        if budget.limit is not None and total_expenses + transaction.amount > budget.limit:
            Notification.create_notification(
                user=user,
                message=f'Вы превысили бюджет для {category}.'
            )
            budget.is_completed = True
            budget.save()

    plans = Plan.objects.filter(user=user)
    for plan in plans:
        total_expenses = Transaction.objects.filter(
            account__user=user
        ).aggregate(total=Sum('amount'))['total'] or 0
        if total_expenses >= plan.amount:
            plan.is_completed = True
            plan.save()
        elif plan.due_date < timezone.now().date():
            plan.is_failed = True
            plan.save()

templates/money_management/add_account.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавить аккаунт</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h2>Добавить аккаунт</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Добавить аккаунт</button>
    </form>
</div>
</body>
</html>

templates/money_management/add_transaction.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавить транзакцию</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h2>Добавить транзакцию</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
</div>
</body>
</html>

templates/money_management/delete_transaction.html
{% extends 'base.html' %}

{% block title %}Удалить транзакцию{% endblock %}

{% block content %}
    <div class="container">
        <h2>Вы уверены, что хотите удалить эту транзакцию?</h2>
        <p>Аккаунт: {{ transaction.account.name }}</p>
        <p>Тип: {{ transaction.type }}</p>
        <p>Сумма: {{ transaction.amount }}</p>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'money_management:index' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

templates/money_management/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Транзакции{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>Транзакции</h2>

        <form method="GET" action="{% url 'money_management:index' %}" class="form-inline" style="float: right; margin-bottom: 10px;">
            <div class="form-group">
                <label for="currency">Валюта:</label>
                <select name="currency" class="form-control ml-2" id="currency" onchange="this.form.submit()">
                    {% for code, name in currency_choices %}
                        <option value="{{ code }}" {% if target_currency == code %}selected{% endif %}>{{ name }} ({{ code }})</option>
                    {% endfor %}
                </select>
            </div>
        </form>

        <div style="clear: both;"></div>

        <a href="{% url 'money_management:add_account' %}" class="btn btn-primary mt-3">Добавить аккаунт</a>
        <a href="{% url 'money_management:add_transaction' %}" class="btn btn-primary mt-3">Добавить транзакцию</a>

        <table class="table mt-4">
            <thead>
                <tr>
                    <th>Аккаунт</th>
                    <th>Тип</th>
                    <th>Прошлый баланс</th>
                    <th>Сумма</th>
                    <th>Нынешний баланс</th>
                    <th>Категория</th>
                    <th>Примечание</th>
                    <th>Дата и время</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody id="transaction-table-body">
                {% for transaction in transactions %}
                    <tr>
                        <td>{{ transaction.account }}</td>
                        <td>{{ transaction.type }}</td>
                        <td>{{ transaction.previous_balance }} {{ target_currency }}</td>
                        <td>{{ transaction.amount }} {{ target_currency }}</td>
                        <td>{{ transaction.current_balance }} {{ target_currency }}</td>
                        <td>{{ transaction.category }}</td>
                        <td>{{ transaction.note }}</td>
                        <td>{{ transaction.created_at }}</td>
                        <td>
                            <a href="{% url 'money_management:update_transaction' pk=transaction.id %}" class="btn btn-sm btn-primary">
                                <i class="fas fa-pencil-alt"></i>
                            </a>
                            <a href="{% url 'money_management:delete_transaction' pk=transaction.id %}" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if page_obj.has_next %}
            <div class="text-center">
                <button id="load-more" class="btn btn-secondary" data-next-page="{{ page_obj.next_page_number }}">Ещё</button>
            </div>
        {% endif %}

        <h2>График транзакций</h2>
        <canvas id="transactionChart" width="400" height="200"></canvas>

        <div class="modal fade" id="addAccountModal" tabindex="-1" aria-labelledby="addAccountModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addAccountModalLabel">Добавить аккаунт</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{% url 'money_management:add_account' %}">
                            {% csrf_token %}
                            {{ account_form|crispy }}
                            <button type="submit" class="btn btn-primary">Добавить аккаунт</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h2>Пожалуйста, войдите или зарегистрируйтесь</h2>
    {% endif %}
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const loadMoreButton = document.getElementById('load-more');
    if (loadMoreButton) {
        loadMoreButton.addEventListener('click', function() {
            let nextPage = this.getAttribute('data-next-page');
            let xhr = new XMLHttpRequest();
            xhr.open('GET', `?page=${nextPage}`, true);
            xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
            xhr.onload = function() {
                if (xhr.status >= 200 && xhr.status < 400) {
                    try {
                        let response = JSON.parse(xhr.responseText);
                        let transactionTableBody = document.getElementById('transaction-table-body');

                        response.transactions.forEach(function(transaction) {
                            let newRow = transactionTableBody.insertRow();
                            newRow.innerHTML = `
                                <td>${transaction.account}</td>
                                <td>${transaction.type}</td>
                                <td>${transaction.previous_balance} ${transaction.currency}</td>
                                <td>${transaction.amount} ${transaction.currency}</td>
                                <td>${transaction.current_balance} ${transaction.currency}</td>
                                <td>${transaction.category}</td>
                                <td>${transaction.note}</td>
                                <td>${transaction.created_at}</td>
                                <td>
                                    <a href="/money_management/update_transaction/${transaction.id}/" class="btn btn-sm btn-primary">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <a href="/money_management/delete_transaction/${transaction.id}/" class="btn btn-sm btn-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>`;
                        });

                        if (response.has_next) {
                            loadMoreButton.setAttribute('data-next-page', response.next_page_number);
                        } else {
                            loadMoreButton.remove();
                        }
                    } catch (e) {
                        console.error('Error parsing JSON response:', e);
                    }
                } else {
                    console.error('Error loading more transactions:', xhr.statusText);
                }
            };
            xhr.onerror = function() {
                console.error('Request failed');
            };
            xhr.send();
        });
    }

    const ctx = document.getElementById('transactionChart').getContext('2d');
    const chartData = JSON.parse('{{ chart_data|escapejs }}');
    console.log(chartData);  // Debugging line
    const transactionChart = new Chart(ctx, {
        type: '{{ chart_type }}',
        data: {
            labels: chartData.labels,
            datasets: [{
                label: 'Транзакции по дням',
                data: chartData.total,
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1,
                fill: false
            }, {
                label: 'Доходы',
                data: chartData.income,
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 1,
                fill: false
            }, {
                label: 'Расходы',
                data: chartData.expense,
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1,
                fill: false
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
});
</script>
{% endblock %}

templates/money_management/update_transaction.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Обновить транзакцию{% endblock %}

{% block content %}
    <div class="container">
        <h2>Обновить транзакцию</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock %}